name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Test database connection
      run: |
        cd backend

    - name: Archive backend files
      run: |
        cd backend
        zip -r ../backend-deploy.zip .

    - name: Deploy to Azure Web App for backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'deliverynote-database'  # Nom App Service backend
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D46343A90614D2EAB7FA22C4A24D500 }}
        package: backend-deploy.zip
