name: Deployement  Backend

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install backend dependencies
      run: |
        cd backend
        npm install
      
    - name: Archive backend files
      run: |
        cd backend
        zip -r ../backend-deploy.zip .

    - name: Deploy to Azure Web App for backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'deliverynotedatabase'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7DC8E30E982D4937975D69AE86D2B164 }}
        package: .
